//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineEducationSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Faculty
    {
        public string FId { get; set; }
        public string FName { get; set; }
        public string FBranch { get; set; }
        public string MobileNumber { get; set; }
        public string Email { get; set; }
        public string Address { get; set; }
        public string FDOB { get; set; }
        public string Qualification { get; set; }
    }
}
