//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineEducationSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HEAD
    {
        public string PId { get; set; }
        public string PName { get; set; }
        public string PDOB { get; set; }
        public string PQualification { get; set; }
        public string PEmail { get; set; }
        public string PMobileNumber { get; set; }
        public string PAddress { get; set; }
    }
}
