//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineEducationSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HOD
    {
        public string HId { get; set; }
        public string HName { get; set; }
        public string HDOB { get; set; }
        public string HBranch { get; set; }
        public string Qualification { get; set; }
        public string HMobileNumber { get; set; }
        public string HEmail { get; set; }
        public string HAddress { get; set; }
    }
}
