//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineEducationSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Student
    {
        public string SId { get; set; }
        public string SName { get; set; }
        public string DOB { get; set; }
        public string FatherName { get; set; }
        public string MotherName { get; set; }
        public string MobileNumber { get; set; }
        public string AlternateMobileNumber { get; set; }
        public string Email { get; set; }
        public string Address { get; set; }
        public string Branch { get; set; }
    }
}
